<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/example.proto

namespace App\GRPC\GPBMetadata;

class Example
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac0010a1370726f746f2f6578616d706c652e70726f746f12076578616d706c65221b0a0353756d12090a016118012001280512090a016218022001280522180a06526573756c74120e0a06726573756c7418012001280532340a0a43616c63756c61746f7212260a0353756d120c2e6578616d706c652e53756d1a0f2e6578616d706c652e526573756c742200422bca02114170705c475250435c5365727669636573e202144170705c475250435c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

